"""Wire-format constants, generated from SPECIFICATION.md's "File Format"
section by ../../tools/generate_constants.py -- do not edit by hand.
"""

verheader = b'centurymetadata v1\x00'
preamble = b'centurymetadata v1\x00SIG[64]|WRITER_PUBKEY[33]|READER_ID[32]|GEN[8]|MLKEM_CT[1568]|AES[14679]\n\nSIG: BIP-340 SHA256(TAG|TAG|WRITER_PUBKEY|READER_ID|GEN|MLKEM_CT|AES)\nWRITER_PUBKEY: BIP-32 0x44315441\'/N\'/0\'\nREADER_SECP_PRIVKEY: BIP-32 0x44315441\'/N\'/1\'\nREADER_SECP_PUBKEY: 33-byte compressed G*READER_SECP_PRIVKEY\nREADER_MLKEM_SEED_D: BIP-32 0x44315441\'/N\'/3\'\nREADER_MLKEM_SEED_Z: BIP-340 SHA256(MLKEM_Z_TAG|MLKEM_Z_TAG|READER_MLKEM_SEED_D)\nMLKEM_Z_TAG: SHA256("centurymetadata v1 mlkem-z"[26])\nREADER_MLKEM_PRIVKEY, READER_MLKEM_PUBKEY: ML-KEM-1024.KeyGen(d=READER_MLKEM_SEED_D,z=READER_MLKEM_SEED_Z)\nREADER_ID: SHA256(READER_SECP_PUBKEY|READER_MLKEM_PUBKEY)\nTAG: SHA256("centurymetadata v1"[18])\nMLKEM_CT: ML-KEM-1024 (FIPS 203) ciphertext encapsulated to reader\'s ML-KEM key\nMLKEM_SECRET: ML-KEM-1024.Decaps(MLKEM_CT, READER_MLKEM_PRIVKEY)\nECDH_SECRET: EC Diffie-Hellman of WRITER_PUBKEY and READER_SECP_PRIVKEY = SHA256(33-byte compressed WRITER_PUBKEY*READER_SECP_PRIVKEY)\nAESKEY: SHA256(ECDH_SECRET|MLKEM_SECRET|GEN)\nAES: AES-256-GCM using AESKEY, 12-byte all-zero nonce, of DATA; 16-byte authentication tag appended\nDATA: ZLIB([TYPE\\0NAME\\0CONTENTS\\0]+), padded with 0 bytes to 14663\x00'

DATA_LENGTH = 16384
MLKEM_CT_LENGTH = 1568
PLAINTEXT_LENGTH = 14663
AES_LENGTH = 14679
RECORD_LENGTH = len(preamble) + DATA_LENGTH
# BIP340 tag excludes final \0
bip340tag = verheader[:-1]
