[project]
name = "centurymetadata"
version = "0.02"
description = "Encrypt, send, retrieve and decrypt centurymetadata.org files"
authors = [
    {name = "Rusty Russell", email = "rusty@rustcorp.com.au"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pycryptodomex>=3.6",
    "secp256k1>=0.14.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.urls]
Homepage = "https://centurymetadata.org/"
Repository = "https://github.com/rustyrussell/centurymetadata/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
